version: "3.8"

services:
  web:
    build: .
    ports:
      - "6000:6000"
    environment:
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/1"
      SESSION_TYPE: "redis"
      SESSION_REDIS: "redis://redis:6379/2"
      FLASK_APP: "app:create_app"
    depends_on:
      - redis
      - celery_worker

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]

  celery_worker:
    build: .
    command: celery -A celery_worker.celery worker --loglevel=info
    environment:
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/1"
    depends_on:
      - redis

volumes:
  redis_data:
